Make Observation partitioned, compressed, columnar and append-only.
To enable partitioning, the following changes to HDM were necessary:

ERROR: cannot mix inheritance with partitioning.

* inheritance was removed.
* as a consequence, HDM was changes to emit explicit definitions of the columns
  of RIM ancestor classes.
* as a consequence, RIM sql contains BIGINT primary keys in addition to
  BIGSERIAL. As _id BIGSERIAL was the trigger for _cluster, add the new case as
  well.

ERROR: PRIMARY KEY constraint must contain all columns in the partition key.

* primary keys where removed, as it was not an option to add _effective_time_*
  columns to the primary key, as there are records with no effective time.
* as a consequence, any foreign key related expressions will now error, instead
  of given the GP warning that they are not supported. Remove all foreign key
  references.